### ISSUE TITLE
Does not work on 2.7 and claims so

### ISSUE THREAD

**Issue by mudrd8mz** [sstreet/moodle-mod_og#2]
In the plugins directory, the plugins claims to support Moodle 2.7 only and in version.php, it declares that it just requires Moodle 2.0 (2010112400).

However, on Moodle 2.7 it does with fatal error: "Call to undefined function get_course_and_cm_from_cmid()".

That function was added only with Moodle 2.8. So please make sure to set correctly which Moodle versions the plugin supports. The version.php must declare the plugin requires 2014111000 at least.

**Comment by sstreet** [comment]
Fixed - changed requirement to Moodle 2.8 in version.php.
