### ISSUE TITLE
Naming conventions

### ISSUE THREAD

**Issue by mudrd8mz** [sstreet/moodle-mod_og#3]
The class `simplehtml_form` does not follow the naming conventions for classes - https://docs.moodle.org/dev/Plugin_contribution_checklist#Namespace_collisions

The class should either be namespaced, or have `mod_og_` or at least `og_` prefix (the last one is sort of legacy exception for activity modules and is discouraged now).

**Comment by sstreet** [comment]
Fixed - This class name is now called `mod_og_form`.
