### ISSUE TITLE
The og_pluginfile() perform more access checks

### ISSUE THREAD

**Issue by mudrd8mz** [sstreet/moodle-mod_og#4]
The main benefit of serving the files directly by plugins via functions like `og_pluginfile()` is that the plugin can (and should) perform appropriate access permissions check before sending the file.

In this case, it seems that any logged in user who knows the URL to the file (which is not hard to guess or find out) could download any file. This has been a big issue in recent versions of the Assignment module and I am afraid it is happening here, too.

I believe the `og_pluginfile()` should make sure that either the user is the owner of the file, or it is a teacher in the course - typically by a new capability like `mod/og:viewallsubmissions` or so, that would be granted to teachers by default.

**Comment by sstreet** [comment]
Fixed - implemented new capability as suggested and only allow users who either created the file or have `mod/og:viewallsubmissions` capability are sent the file.
